package com.deepanshu.backend.activitylog.entity;

public enum ActivityAction {

    WORKSPACE_CREATED,
    WORKSPACE_UPDATED,
    WORKSPACE_DELETED,

    MEMBER_ADDED,
    MEMBER_REMOVED,
    MEMBER_ROLE_CHANGED,

    PROJECT_CREATED,
    PROJECT_UPDATED,
    PROJECT_DELETED,

    BOARD_CREATED,
    BOARD_UPDATED,
    BOARD_DELETED,

    TASK_CREATED,
    TASK_UPDATED,
    TASK_DELETED,
    TASK_ASSIGNED,
    TASK_UNASSIGNED,
    TASK_STATUS_CHANGED,
    TASK_MOVED,

    COMMENT_CREATED,
    COMMENT_EDITED,
    COMMENT_DELETED,
}